### ISSUE TITLE
No funciona el primer ejemplo de la tarea en repl.it

### ISSUE THREAD

**Issue by Cesar-63** [ICF222/Laboratorio#6]
Al intentar ejecutar el main.py en repl.it con  el comando "python main.py --vision 11 --map maps/ca_cave.map --start_pos 122.208 --goal_pos 125.209 --out camino.out" el programa entrega el siguiente error:

File "<stdin>", line 1
    python main.py --vision 11 --map maps/ca_cave.map --start_pos 122.208 --goal_pos 125.209 --out camino.out
           ^
SyntaxError: invalid syntax

He intentado diferentes cambios en el comando, pero lo único que varía es la posición del "^" la cual parece no indicar nada.

El código es el mismo inicial, no le he cambiado nada.

Gracias.

**Comment by alphadx** [comment]
Hola Cesar, creo que lo siguiente puede ser una solución.
Si tu problema es el siguiente.
![imagen](https://user-images.githubusercontent.com/5598428/95767736-908bca80-0c8b-11eb-8acb-18e53a4c6d00.png)
es porque esa consola es una consola de Python.  Eso quiere decir que ya estás dentro de Python.
Bien podrías buscar como **ejecutar con argumentos en repl.it**
O bien, podrías probar en un a BASH, con todos los archivos.  Puede ser una _BASH virtual_, como las que entrega repl.it
[https://repl.it/languages/bash](https://repl.it/languages/bash)
Y si pones tus archivos ahí, no tendrás problema en ejecutar llamar a Python
![Ejecución en BASH virtual](https://user-images.githubusercontent.com/5598428/95768030-114ac680-0c8c-11eb-86bc-058d7577710f.png)

Sólo requieres copiar tus archivos de un lado a otro.
Espero te sea de ayuda.

Slds!

**Comment by Cesar-63** [comment]
Ahí funciona bien, muchas gracias!
